# Generated by Django 2.1.7 on 2019-03-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20190302_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
